=== pharriso/summit-connect-eda-2024/apps/toomanyapperrors/src/main/resources/sensuevent.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "check": {
      "type": "object",
      "properties": {
        "command": {
          "type": "string"
        },
        "handlers": {
          "type": "array",
          "items": [
            {
              "type": "string"
            }
          ]
        },
        "subscriptions": {
          "type": "array",
          "items": [
            {
              "type": "string"
            }
          ]
        },
        "output": {
          "type": "string"
        },
        "state": {
          "type": "string"
        },
        "status": {
          "type": "integer"
        },
        "total_state_change": {
          "type": "integer"
        },
        "last_ok": {
          "type": "integer"
        },
        "occurrences": {
          "type": "integer"
        },
        "occurrences_watermark": {
          "type": "integer"
        },
        "metadata": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "namespace": {
              "type": "string"
            }
          }
        }
      }
    },
    "entity": {
      "type": "object",
      "properties": {
        "entity_class": {
          "type": "string"
        },
        "system": {
          "type": "object",
          "properties": {
            "hostname": {
              "type": "string"
            },
            "os": {
              "type": "string"
            },
            "platform": {
              "type": "string"
            },
            "platform_family": {
              "type": "string"
            },
            "platform_version": {
              "type": "string"
            },
            "arch": {
              "type": "string"
            },
            "libc_type": {
              "type": "string"
            }
          }
        },
        "subscriptions": {
          "type": "array",
          "items": [
            {
              "type": "string"
            },
            {
              "type": "string"
            },
            {
              "type": "string"
            }
          ]
        },
        "last_seen": {
          "type": "integer"
        },
        "user": {
          "type": "string"
        },
        "metadata": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "namespace": {
              "type": "string"
            },
            "labels": {
              "type": "object",
              "properties": {
                "location": {
                  "type": "string"
                },
                "rack": {
                  "type": "string"
                }
              }
            },
            "created_by": {
              "type": "string"
            }
          }
        },
        "sensu_agent_version": {
          "type": "string"
        }
      }
    },
    "id": {
      "type": "string"
    },
    "metadata": {
      "type": "object",
      "properties": {
        "namespace": {
          "type": "string"
        }
      }
    },
    "timestamp": {
      "type": "integer"
    }
  }
}

=== pharriso/summit-connect-eda-2024/apps/throttle/src/main/resources/testdata.json
{"check":{"command":"check-http.rb -u https://hub.demolab.local/ui/login -w","handlers":["kafka"],"high_flap_threshold":0,"interval":60,"low_flap_threshold":0,"publish":true,"runtime_assets":["sensu-plugins/sensu-plugins-http","sensu/sensu-ruby-runtime"],"subscriptions":["hub"],"proxy_entity_name":"","check_hooks":null,"stdin":false,"subdue":null,"ttl":0,"timeout":0,"round_robin":false,"duration":0.129471317,"executed":1709050520,"history":[{"status":0,"executed":1709050388},{"status":2,"executed":1709050403},{"status":2,"executed":1709050417},{"status":2,"executed":1709050477},{"status":0,"executed":1709050520}],"issued":1709050520,"output":"CheckHttp OK: 200, 360 bytes\n\u003c!doctype html\u003e\u003chtml lang=\"en-US\"\u003e\u003chead\u003e\u003cmeta charset=\"UTF-8\"\u003e\u003ctitle\u003eAutomation Hub\u003c/title\u003e\u003clink rel=\"icon\" href=\"/static/galaxy_ng/favicon.ico\"\u003e\u003cscript defer=\"defer\" src=\"/static/galaxy_ng/js/App.5489105562cd9da1a2a2.js\"\u003e\u003c/script\u003e\u003clink href=\"/static/galaxy_ng/css/App.be73969e312997e46cd3.css\" rel=\"stylesheet\"\u003e\u003c/head\u003e\u003cbody\u003e\u003cdiv id=\"root\"\u003e\u003c/div\u003e\u003c/body\u003e\u003c/html\u003e\n","state":"passing","status":0,"total_state_change":0,"last_ok":1709050520,"occurrences":1,"occurrences_watermark":3,"output_metric_format":"","output_metric_handlers":null,"env_vars":null,"metadata":{"name":"check-hub-https","namespace":"default"},"secrets":null,"is_silenced":false},"entity":{"entity_class":"agent","system":{"hostname":"dev","os":"linux","platform":"redhat","platform_family":"rhel","platform_version":"8.9","network":{"interfaces":[{"name":"lo","addresses":["127.0.0.1/8","::1/128"]},{"name":"ens192","mac":"00:50:56:93:ee:c6","addresses":["10.50.0.126/22","fe80::250:56ff:fe93:eec6/64"]}]},"arch":"amd64","libc_type":"glibc","vm_system":"","vm_role":"","cloud_provider":"","processes":null},"subscriptions":["system","entity:dev.demolab.local","hub"],"last_seen":1709050520,"deregister":false,"deregistration":{},"user":"agent","redact":["password","passwd","pass","api_key","api_token","access_key","secret_key","private_key","secret"],"metadata":{"name":"dev.demolab.local","namespace":"default","labels":{"location":"swindon","rack":"rack1"},"created_by":"admin"},"sensu_agent_version":"6.6.6"},"id":"1b29fa20-1ca2-4013-9c6c-7d82ca2388c3","metadata":{"namespace":"default"},"timestamp":1709050520}
